// Mock Food Items Data

export const MOCK_FOOD_ITEMS = [
  // Appetizers
  {
    id: 'appetizer-1',
    name: 'Garlic Bread',
    description: 'Crispy bread with garlic butter and herbs',
    price: 4.99,
    category: 'Appetizers',
    image: 'https://via.placeholder.com/300x200?text=Garlic+Bread',
    ingredients: ['Bread', 'Garlic', 'Butter', 'Herbs'],
    allergens: ['Gluten'],
    available: true,
  },
  {
    id: 'appetizer-2',
    name: 'Mozzarella Sticks',
    description: 'Golden fried mozzarella cheese sticks with marinara sauce',
    price: 5.99,
    category: 'Appetizers',
    image: 'https://via.placeholder.com/300x200?text=Mozzarella+Sticks',
    ingredients: ['Mozzarella', 'Flour', 'Egg', 'Oil'],
    allergens: ['Gluten', 'Dairy'],
    available: true,
  },
  {
    id: 'appetizer-3',
    name: 'Buffalo Wings',
    description: 'Crispy chicken wings tossed in buffalo sauce',
    price: 6.99,
    category: 'Appetizers',
    image: 'https://via.placeholder.com/300x200?text=Buffalo+Wings',
    ingredients: ['Chicken', 'Buffalo Sauce', 'Oil'],
    allergens: [],
    available: true,
  },

  // Main Course
  {
    id: 'main-1',
    name: 'Classic Burger',
    description: 'Juicy beef patty with lettuce, tomato, and special sauce',
    price: 12.99,
    category: 'Main Course',
    image: 'https://via.placeholder.com/300x200?text=Classic+Burger',
    ingredients: ['Beef', 'Lettuce', 'Tomato', 'Bun', 'Sauce'],
    allergens: ['Gluten'],
    available: true,
  },
  {
    id: 'main-2',
    name: 'Grilled Salmon',
    description: 'Fresh salmon fillet with seasonal vegetables',
    price: 16.99,
    category: 'Main Course',
    image: 'https://via.placeholder.com/300x200?text=Grilled+Salmon',
    ingredients: ['Salmon', 'Vegetables', 'Olive Oil', 'Lemon'],
    allergens: ['Fish'],
    available: true,
  },
  {
    id: 'main-3',
    name: 'Pasta Carbonara',
    description: 'Creamy pasta with bacon and parmesan cheese',
    price: 13.99,
    category: 'Main Course',
    image: 'https://via.placeholder.com/300x200?text=Pasta+Carbonara',
    ingredients: ['Pasta', 'Bacon', 'Eggs', 'Parmesan', 'Cream'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    available: true,
  },
  {
    id: 'main-4',
    name: 'Margherita Pizza',
    description: 'Classic pizza with mozzarella, tomato, and basil',
    price: 11.99,
    category: 'Main Course',
    image: 'https://via.placeholder.com/300x200?text=Margherita+Pizza',
    ingredients: ['Dough', 'Tomato', 'Mozzarella', 'Basil', 'Olive Oil'],
    allergens: ['Gluten', 'Dairy'],
    available: true,
  },

  // Desserts
  {
    id: 'dessert-1',
    name: 'Chocolate Cake',
    description: 'Rich chocolate cake with chocolate frosting',
    price: 6.99,
    category: 'Desserts',
    image: 'https://via.placeholder.com/300x200?text=Chocolate+Cake',
    ingredients: ['Flour', 'Cocoa', 'Eggs', 'Sugar', 'Butter'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    available: true,
  },
  {
    id: 'dessert-2',
    name: 'Cheesecake',
    description: 'Creamy cheesecake with berry topping',
    price: 7.99,
    category: 'Desserts',
    image: 'https://via.placeholder.com/300x200?text=Cheesecake',
    ingredients: ['Cream Cheese', 'Sugar', 'Eggs', 'Crust', 'Berries'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    available: true,
  },
  {
    id: 'dessert-3',
    name: 'Tiramisu',
    description: 'Italian dessert with coffee and mascarpone',
    price: 5.99,
    category: 'Desserts',
    image: 'https://via.placeholder.com/300x200?text=Tiramisu',
    ingredients: ['Mascarpone', 'Coffee', 'Cocoa', 'Ladyfingers'],
    allergens: ['Dairy', 'Eggs'],
    available: true,
  },

  // Beverages
  {
    id: 'beverage-1',
    name: 'Coca Cola',
    description: 'Classic cola drink',
    price: 2.99,
    category: 'Beverages',
    image: 'https://via.placeholder.com/300x200?text=Coca+Cola',
    ingredients: ['Carbonated Water', 'Sugar', 'Caramel Color'],
    allergens: [],
    available: true,
  },
  {
    id: 'beverage-2',
    name: 'Orange Juice',
    description: 'Fresh squeezed orange juice',
    price: 3.99,
    category: 'Beverages',
    image: 'https://via.placeholder.com/300x200?text=Orange+Juice',
    ingredients: ['Oranges'],
    allergens: [],
    available: true,
  },
  {
    id: 'beverage-3',
    name: 'Iced Coffee',
    description: 'Cold brew coffee with ice',
    price: 4.49,
    category: 'Beverages',
    image: 'https://via.placeholder.com/300x200?text=Iced+Coffee',
    ingredients: ['Coffee', 'Water', 'Ice'],
    allergens: [],
    available: true,
  },
];

export default MOCK_FOOD_ITEMS;
